directories:
  output: release
  buildResources: build
asar: false
npmRebuild: false
appId: com.boatrace.manager
productName: BoatRaceManager
files:
  - filter:
      - electron/**/*
      - modules/**/*
      - angular/dist/**/*
      - routes/**/*
      - public/**/*
      - db/**/*
      - xml/**/*
      - '*.js'
      - '*.json'
      - .env
      - node_modules/**/*
      - '!release/**/*'
      - '!dist/**/*'
      - '!node_modules/.cache/**/*'
win:
  target: nsis
electronVersion: 42.0.0
